import type { Metadata } from "next";
import ParticleBackground from "../components/ParticleBackground";
import NavBar from "../components/NavBar";
import "./globals.css";


export const metadata: Metadata = {
  title: "University System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <NavBar />
        <ParticleBackground />
        {children}

      </body>
    </html>
  );
}
